source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'zhangchu' do
    pod 'SnapKit','~>0.22.0'
    pod 'Kingfisher','~>2.6.0'
    pod 'XWSwiftRefresh','~>0.1.9'
    pod 'SwiftyJSON','~>2.4.0'  
    pod 'Alamofire'
end
